### ISSUE TITLE
Warning when tagging sections.

### ISSUE THREAD

**Issue by simurgh9** [latex3/tagpdf#61]
The file [tagpdf.tex](https://github.com/u-fischer/tagpdf/blob/5353d2888114145b909a7e76d8f676cb503af2a2/doc/tagpdf.tex) uses,

`\DocumentMetadata{pdfversion=2.0,lang=en-UK,testphase=phase-II,testphase=toc-tagging,testphase=sec-tagging,pdfstandard=a-2b}`

So I added the following to my document,

```
\DocumentMetadata{
  pdfversion=2.0,
  lang=en-UK,
  testphase=phase-II,
  testphase=sec-tagging
}
```
I thought this will automatically tag sections. But unfortunately I get a warning,

`LaTeX DocumentMetadata Warning: LaTeX-lab package 'sec-tagging' not found.`

Am I suppose to manually download that package somehow? I made sure that the tagpdf was at `cat-version: 0.98a` by `tlmgr info tagpdf`.

**Comment by u-fischer** [comment]
The sec-tagging and toc-tagging code is not public currently; it will be moved to latex-lab later. The code used for the footnotes is currently in a branch in the latex github. I used all this on the documentation to be able to ask some people for feedback about the tagging (0.98 had actually an error, the section numbers where missing in the tagging ...).

**Comment by FrankMittelbach** [comment]
@u-fischer I think it is a natural assumption that the source code of the documentation can be reused. If that is often not the case because of intermediate stages of the development I would suggest to put in a notice near \DocumentMetadata explicitly stating that the documentation may have been produced with code not yet publically available and that therefore the key settings used there are likely to be not reusable.

However, I would personally suggest not to use the documentation as a testbed for future functionality but to provide that separately (as just pdfs, maybe). After all, it seems good to me if people can reprocess the documentation and get a valid document.

**Comment by u-fischer** [comment]
@FrankMittelbach I added a note and enabled the "untagged documentation". 

> However, I would personally suggest not to use the documentation as a testbed for future functionality

well it is a good testbed for me as it shows me in a real document both what works and what doesn't or is awkward ;-)

**Comment by FrankMittelbach** [comment]
understood :-) but in that case I would put in a disclaimer into the source to say that

**Comment by simurgh9** [comment]
> The sec-tagging and toc-tagging code is not public currently; it will be moved to latex-lab later.

Are there any estimates of how soon this maybe?

**Comment by u-fischer** [comment]
@simurgh9 the code is now public, currently in the testnewpara branch of the latex github, but it will be merged into develop and got to ctan hopefully soon. Be aware that this is a first step. It won't work with arbitrary classes or arbitrary packages (feedback about problems is welcome), and it is bound to change.
